### ISSUE TITLE
Rules should be validated before import

### ISSUE THREAD

**Issue by lazyvab** [requestly/chrome-extension#101]
Currently any invalid json object can be imported in Requestly as an active rule with empty name or type.

**Comment by blunderboy** [comment]
@lazyvab I will pick this one. We need to migrate existing validation code from view to model and add the validation when importing rules.

**Comment by jainrahul983** [comment]
@blunderboy can a file be imported having multiple rules? if yes, if user tries to import the rules and one rule doesn't follow the standard validations like (name is empty) what to do in that scenario??

**Comment by blunderboy** [comment]
@jainrahul983 Good Question!! Yes, a file can contain multiple rules. If a rule is invalid due to any reason, lets just skip it. Lets follow this table:

| Case | Message | Message Type |
|---------|-------------| ---------------------|
| All Rules are valid | N Rules imported successfully | Success (Green) |
| Some Rules (M) are valid | M out of N Rules imported successfully | Info (Blue) |
| All rules are invalid | Invalid Rules can not be imported | Error (Red) | 

Does that make sense ?

**Comment by jainrahul983** [comment]
@blunderboy  ok seems fine for now. :)

**Comment by blunderboy** [comment]
@jainrahul983 Thanks for the PR. Lets improve that PR and re-generate it with proper fixes and code conventions. Please add "In Progress" label when you are working on ticket and remove it when you are done. I am adding it for now.

**Comment by blunderboy** [comment]
This has been fixed with this commit. https://github.com/requestly/chrome-extension/commit/f0836afdca05a878bee9a8f79a272ef55d41fb02

Closing this.
