### ISSUE TITLE
User should be able to save a rule and stay on editor screen

### ISSUE THREAD

**Issue by VarunAgw** [requestly/chrome-extension#114]
While testing something, it can be very handy to apply changes without closing the page.

There can be three buttons side by side: `Cancel`, `Apply` `Save/OK`

**Comment by blunderboy** [comment]
Hmm...Sounds useful to me as well. Would you like to make this contribution ?
I'd try to provide whatever help you need. Let me know if you are interested otherwise I will take it up.

**Comment by VarunAgw** [comment]
Sorry, I'm busy these days so I cannot contribute. Beside I don't have understanding of Chrome extensions, so doing this will take much more time for me

**Comment by blunderboy** [comment]
@VarunAgw No problem. I will work towards fixing it.

**Comment by blunderboy** [comment]
Here is the proposed solution:

Instead of "Cancel" and "Save" buttons, we are going to have the following "Apply" and "Save" buttons.
Apply: Save current set of changes but remain on same screen
Save: (No Change) Save changes and go to List screen

Introduce a "X" icon on top right to perform the "Cancel" action.

**Comment by blunderboy** [comment]
All subtasks are complete. Merging back to master and closing this issue.

**Comment by blunderboy** [comment]
@VarunAgw This change is now available to public. Can you check it quickly and share your feddback ?
