### ISSUE TITLE
Changing Source URL type cause scroll to top

### ISSUE THREAD

**Issue by VarunAgw** [requestly/chrome-extension#119]
Steps to reproduce:

A) Create a "Redirect Request Rule" with many "Source Destination Pairs"
B) Navigate to the last one
C) Click default Source type "Contains" and change it to anything else
D) Page will get scroll back to top requiring you to manually scroll to bottom

**Comment by blunderboy** [comment]
Thanks @VarunAgw for logging this. This happens because changing dropdown value, changes the RuleModel and this further renders the view again. When a view is rendered, view gets all the state from model and scrollPosition is something which is not (and should not) be stored in model and thus difficult to fix in current code design.

Another elegant way to fix is that RuleModel should have collection of pairs (Pair is source-destination pair in Redirect Rule) instead of just array and when when a dropdown value is changed, only that particular pairModel will re-render and hence scroll position will get maintained.

But this requires good amount of code change. Can we live with this or do you really really get this fixed ?

**Comment by VarunAgw** [comment]
It was just a minor issue. Definitely not so important.

**Comment by blunderboy** [comment]
Thanks @VarunAgw . Closing this for now. I will reopen if required.
