### ISSUE TITLE
Conversion to complete offline version

### ISSUE THREAD

**Issue by VarunAgw** [requestly/chrome-extension#120]
Currently it doesn't work without internet. It will be much better/simpler if it works completely offline like a normal chrome extension

Just a suggestion!

**Comment by blunderboy** [comment]
@VarunAgw Requestly used to work offline around 6 months back. I have introduced the online version intentionally. See, Requestly is all about Network requests and I know there can be use cases when you have locally hosted server. But I want to maintain this online version because it gives so much flexibility.
I do not need to publish a new version even if I want to update message in footer.
Moreover, Chrome extension can not work with Google Adsense So I thought of this approach to introduce adsense and any other monetization strategy I want to follow.

Hope it helps!! I will seek some solution to it depending upon the number of requests for this.

**Comment by blunderboy** [comment]
@VarunAgw I am sorry but I cannot complete this request. Can we close this ticket ?

**Comment by VarunAgw** [comment]
Sure!
