### ISSUE TITLE
Response headers are not added

### ISSUE THREAD

**Issue by avodonosov** [requestly/chrome-extension#137]
I have a rule to add response headers - but when I look at the Dev Tools, the response header is not added. If I change the rule from Response to Request, the header is added.

**Comment by avodonosov** [comment]
No, it seems working, the headers are just not visible in the Dev Tools. 

Sorry for the noise and thanks for the great extension.

**Comment by sachinjain024** [comment]
@avodonosov Yeah, This is a chromium bug that any modification in Response Headers are not visible in Chrome Dev Tools. Check this out: https://bugs.chromium.org/p/chromium/issues/detail?id=258064

I already have an issue open to show some kind of message so that users don't fall into this trap again and again. https://github.com/requestly/chrome-extension/issues/127
